cc_test(
    name = "solar_test",
    srcs = ["test_solar_doomsday.cpp"],
    deps = ["@com_github_google_googletest//:gtest", "@com_github_google_googletest//:gtest_main", "//katas/solar:solar_doom"]
)