# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
  name = "longest_uniq_substring",
  srcs = ["longest_uniq_substring.cpp", "longest_uniq_substring.h", "longest_solution.cpp"],
  ##copts = [],
  ##deps = ["libraries to be linked"],
)

