[package]
name = "calculate_pi"
version = "0.1.0"
authors = ["rotifier <71174694+rotifier@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.7.0"
plotters = "^0.3.0"